# site
title: AcyOrt
description: A Node.js blog tool powered by GitHub.
keywords: acyort, nodejs, blog
rss: rss.xml
favicon: icon.png

# site url. you can set as 'http://yoursite.com/child' if need
# please add 'http://' or 'https://'
url: http://acyortjs.github.io

# comment
disqus: acyort
duoshuo:

# language
language: zh-CN

# theme
theme: ccc45

# pagination
# set 0 if not paging
per_page: 3
archives_per_page: 30

# thumbnail mode
# 1: use the first image as thumbnail and remove the image
# 2: use the first image as thumbnail but not remove the image
thumbnail_mode: 2

# table of content
toc: true

#menu
menu:
  home: /
  archives: /archives/
  tags: /tag/
  categories: /category/

# category
default_category: uncategorized

# blogroll
blogroll:
  GitHub: https://github.com
  Google: https://www.google.com

# social
social:
  email: LoeiFy@gmail.com
  github: https://github.com

# html output directory or child directory e.g. 'child'
public_dir:

# category directory
category_dir:

# tag directory
tag_dir:

# post directory
post_dir:

# archives directory
archives_dir:

# source
# site content source
# your github username/repository
# username
user: acyortjs
# repository
repository: acyortjs.github.io

# site post authors filter
authors:
  - LoeiFy
#  - author0
#  - author1

# GitHub access token(optional)
# token should be separated by '#' if you push this file to GitHub
# token: s#d46a6d65aasd8sdbn

# json output
# boolean or string
# you can set json output path
json: false

# dev mode
dev: false
