# Base Config

# site
# default "AcyOrt", "A Node.js blog tool powered by GitHub."
title:
description:

# rss
# set false if not need rss output
# default "rss.xml"
rss:

# site url. you can set as 'http://yoursite.com/child' if necessary
# please add 'http://' or 'https://'
# default "https://acyortjs.github.io"
url:

# theme
# default "ccc45"
theme:

# pagination
# set 0 if not need
# default 10
per_page: 3

# menu
menu:
  # archives: /archives/
  # categories: /category/
  # tags: /tag/

# category
# default "uncategorized"
default_category:

# html output directory or child directory e.g. 'child'
# default "/"
public_dir:

# site content source
# your github user/repository
# default "acyortjs", "acyortjs.github.io"
user: LoeiFy
repository: Recordum


# Advance Config
# you can ignore it

# blog post authors
# github username
authors:
#  - author0
#  - author1

# timezone
# the timezone of your website
# example: America/New_York, Japan, or UTC
# default is local system timezone
timezone:

# language
# requires theme support
language:

# code line numbers
# whether to dispaly code line numbers
# default true
line_numbers: false

# archives pagination
# set 0 if not need
# default 30
archives_per_page: 3

# post order
# order by create time" or "update time"
# created: use "create time"
# updated: use "update time"
# default "created"
order:

# thumbnail mode
# 1: use the first image as thumbnail and remove the image
# 2: use the first image as thumbnail but not remove the image
# default 2
thumbnail_mode:

# category directory
# default "category"
category_dir:

# tag directory
# default "tag"
tag_dir:

# post directory
# default "posts"
post_dir:

# archives directory
# default "archives"
archives_dir:

# gitHub access token(optional)
# token should be separated by '#' if you push this file to github
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token:

# json output
# boolean or string
# you can set json output path
# default false
json:

# dev mode
# default false
dev:


# Other Config
# customize some settings if necessary

# disqus:
# keywords:
# favicon:
