# Base

# site
title: AcyOrt
description: A Node.js blog tool powered by GitHub.

# url
# you can set as "http://yoursite.com/child" if necessary
# don not forget to add "http://" or "https://"
url:

# theme
# default is "ccc45"
theme:

# pagination
# Number
# set 0 if not need
# default is 10
per_page: 3

# menu
menu:
  categories: /categories/
  tags: /tags/
  about: /about/

# default category
# default is "uncategorized"
default_category:

# content
# the repository's issues
# GitHub user/repository
user: LoeiFy
repository: Recordum


# Advance

# scripts
# script file name
scripts:
  # - example.js

# plugins
plugins:
  # - xxx module

# output
# html output directory
# you can set child directory e.g. "child"
public_dir: /

# authors
# GitHub user
authors:
#  - author0
#  - author1

# timezone
# example: "America/New_York", "Japan", "UTC", or "Asia/Shanghai"
# default is local system timezone
timezone:

# language
# requires theme support
# default is "default"
language:

# code line numbers
# Boolean
# whether to dispaly code line numbers
# default is true
line_numbers:

# order
# order by issues create time" or "update time"
# created: use "create time"
# updated: use "update time"
# default is "created"
order:

# directory
# default is "categories", "tags", "posts"
category_dir:
tag_dir:
post_dir:

# token
# github access token
# token should be separated by '#' if you push this file to github
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token:

# cache
# Boolean
# cache github issues data
# for development
cache:

# Other
# customize some settings if necessary

# disqus:
# favicon:
